name: OWASP ZAP DAST Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zapjob:
    runs-on: ubuntu-latest
    name: Run OWASP ZAP Full Scan

    steps:
      - name: Start ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: 'https://my-zap-demo.vercel.app/'
          fail_action: false
          allow_issue_writing: false

      - name: Upload ZAP Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: zap_report_html
          path: report_html.html

      - name: Upload ZAP Report (JSON)
        uses: actions/upload-artifact@v4
        with:
          name: zap_report_json
          path: report_json.json

      - name: Upload ZAP Report (Markdown)
        uses: actions/upload-artifact@v4
        with:
          name: zap_report_md
          path: report_md.md
