name: OWASP ZAP DAST Scan

permissions:
  issues: write


on:
  push:
    branches: [master]  

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run ZAP Full Scan on Live App
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://my-zap-demo.vercel.app'
          fail_action: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-html-report
          path: report_html.html
