name: ZAP Full Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Full Scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up report files
        run: |
          touch report_json.json report_md.md report_html.html
          chmod a+w report_json.json report_md.md report_html.html

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: 'https://my-zap-demo.vercel.app/'
          format: openapi
          cmd_options: >
            -J report_json.json
            -w report_md.md
            -r report_html.html

      - name: Upload ZAP Scan Report Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-report
          path: |
            report_json.json
            report_md.md
            report_html.html
