name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [master]  # or use pull_request, schedule, etc.

jobs:
  zap_scan:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Application (example with Docker Compose)
        run: |
          docker-compose up -d
          sleep 30  # Wait for the app to fully start (adjust as needed)

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://my-zap-demo.vercel.app' 
          fail_action: false               
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: report_html.html
