name: OWASP ZAP DAST Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run OWASP ZAP Full Scan

    steps:
      - name: Start ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: 'https://my-zap-demo.vercel.app/'
          fail_action: false          # Set true if you want to fail workflow on alerts
          allow_issue_writing: false  # Don't create GitHub issues automatically

      - name: Upload ZAP Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-html
          path: report_html.html

      - name: Upload ZAP Report (JSON)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-json
          path: report_json.json

      - name: Upload ZAP Report (Markdown)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-md
          path: report_md.md
