name: OWASP ZAP Auto Scan

on:
  push:
    branches:
      - main              
  schedule:
    - cron: '0 1 * * *'   
  workflow_dispatch:  

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'https://my-zap-demo.vercel.app/' 
        fail_action: false                  
        cmd_options: '-a'                  

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: owasp-zap-report.html
